runtime: python27 # -_-
api_version: 1
threadsafe: true

handlers:
    - url: /.*
      script: malcat.client.app

env_variables:
      URLFETCH_TIMEOUT: 3
      URLFETCH_USE_HTTPS: yes
      MEMCACHE_TIMEOUT: 900

libraries:
    - name: lxml
      version: "2.3.5"
    - name: yaml
      version: "3.10"
