more = '#more${id} { background-image: url($series_image); }'
animetitle = '.animetitle[href*="$list/$id/"] { background-image: url($series_image); }'
animetitlebefore = '.animetitle[href*="$list/$id/"]:before { background-image: url($series_image); }'
datatitle = '.data.title [href^="/$list/$id/"] { background-image: url($series_image); }'
datatitlebefore = '.data.title [href^="/$list/$id/"]:before { background-image: url($series_image); }'
